#ifndef CONFIG_H
#define CONFIG_H

#define DECORATION_NAME "decoration"
#define DECORATION_HEIGHT 30
#define RESIZE_MARGIN 10

#define WINDOW_LIST_OVERLAY "alttab"
#define WINDOW_LIST_ENTRY_HEIGHT 30

#define MAX_NUKLEAR_VERTEX_MEMORY 512 * 1024
#define MAX_NUKLEAR_ELEMENT_MEMORY 128 * 1024

#define DOUBLE_CLICK_THRESHOLD 0.5
#define COORDS_THRESHOLD 5

#endif
